### ISSUE TITLE
bungled path when setting up and creating a new base

### ISSUE THREAD

**Issue by Culsu** [TLINDEN/jaildk#2]
Hi there,
using the setup routine and installing a new base leads to a bungled path:
jaildk:892 the jaildk_base function is called:
`jaildk_base $j/base/$os`
$j/base/$os does already contain the complete path (e.g. /jail/base/12.2-RELEASE)
Looking at the jaildk_base function the path is doubled (line 303- ~310):
```
jaildk_base() {
    base=$1
if echo "$base" | egrep -q "^/"; then
        basedir=$j/base/$base
    else
        basedir=$base
    fi
```
This leads to a bungled path (e.g. /jail/base//jail/base/12.2-RELEASE).
I'd guess that if is unnecessary and should be removed?

Cheers
FS

**Comment by TLINDEN** [comment]
`-v` is missing there, dammit :)
