### ISSUE TITLE
jaildk status throws an error and columns are missaligned

### ISSUE THREAD

**Issue by Culsu** [TLINDEN/jaildk#27]
When running jaildk status it somehow prints "jail v6 not found".
Also the columns are missaligned.

Already fixed. PR incoming.

#./jaildk status vpnudp
jls: jail "v6" not found
Status  vpnudp:
Jail     IP-Address    Path      Is-Running  RW-mounted  Current-Version  Base
vpnudp     172.16.2.254  yes,jid=  yes         20241014    14.1-RELEASE-p5
Jail vpnudp rc status:
openvpn is running as pid 42965.

**Comment by TLINDEN** [comment]
Ah, I had removed all references to perl and in the process put this line in there. And I had a test jail names `v6`. So I just copied my command unaltered :)

Thanks a lot!
